In [67]:
import pandas as pd
import numpy as np

In [68]:
df = pd.read_csv("zomato.csv")

In [69]:
df.head()

,Restaurant_Name,Dining_Rating,Delivery_Rating,Dining Votes,Delivery_Votes,Cuisine,Place_Name,City,Item_Name,Best_Seller,Votes,Prices
0,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Platter Kebab Combo,BESTSELLER,84,249.0
1,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Rumali Shawarma,BESTSELLER,45,129.0
2,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Tandoori Salad,NaN,39,189.0
3,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken BBQ Salad,BESTSELLER,43,189.0
4,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Special Doner Wrap Combo,MUST TRY,31,205.0

In [70]:
print("Rows = ",df.shape[0])

Rows =  123657

In [71]:
print("Columns = ",df.shape[1])

Columns =  12

In [72]:
print("Unique Restaurant Names = ", df["Restaurant_Name"].nunique())

Unique Restaurant Names =  826

In [73]:
print("Unique Restaurant Names = ", df["City"].nunique())

Unique Restaurant Names =  17

In [74]:
print("Unique Restaurant Names = ", df["Place_Name"].nunique())

Unique Restaurant Names =  324

In [75]:
df.columns

Index(['Restaurant_Name', 'Dining_Rating', 'Delivery_Rating', 'Dining Votes',
       'Delivery_Votes', 'Cuisine ', 'Place_Name', 'City', 'Item_Name',
       'Best_Seller', 'Votes', 'Prices'],
      dtype='object')

In [76]:
print("Unique Restaurant Names = ", df["Cuisine "].nunique())

Unique Restaurant Names =  48

In [77]:
print("Unique Restaurant Names = ", df["Item_Name"].nunique())

Unique Restaurant Names =  55693

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123657 entries, 0 to 123656
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Restaurant_Name  123657 non-null  object
 1   Dining_Rating    91421 non-null   float64
 2   Delivery_Rating  122377 non-null  float64
 3   Dining Votes     123657 non-null  int64
 4   Delivery_Votes   123657 non-null  int64
 5   Cuisine          123657 non-null  object
 6   Place_Name       123657 non-null  object
 7   City             123657 non-null  object
 8   Item_Name        123657 non-null  object
 9   Best_Seller      27942 non-null   object
 10  Votes            123657 non-null  int64
 11  Prices           123657 non-null  float64
dtypes: float64(3), int64(3), object(6)
memory usage: 11.3+ MB

In [79]:
df.describe()

,Dining_Rating,Delivery_Rating,Dining Votes,Delivery_Votes,Votes,Prices
count,91421.000000,122377.000000,123657.000000,123657.000000,123657.000000,123657.000000
mean,3.822264,3.963184,152.729858,115.763725,24.666772,241.378399
std,0.408693,0.245900,232.214061,243.970828,125.236009,192.830713
min,2.500000,2.500000,0.000000,0.000000,0.000000,0.950000
25%,3.600000,3.800000,0.000000,0.000000,0.000000,130.000000
50%,3.900000,4.000000,30.000000,0.000000,0.000000,208.570000
75%,4.100000,4.100000,217.000000,23.000000,15.000000,299.000000
max,4.800000,4.600000,997.000000,983.000000,9750.000000,12024.000000

In [80]:
df.isna().sum()

Restaurant_Name        0
Dining_Rating      32236
Delivery_Rating     1280
Dining Votes           0
Delivery_Votes         0
Cuisine                0
Place_Name             0
City                   0
Item_Name              0
Best_Seller        95715
Votes                  0
Prices                 0
dtype: int64

In [81]:
print("Percentage of Best Seller Missing = ", ((df["Best_Seller"].isna().sum()) / len(df))*100)

Percentage of Best Seller Missing =  77.40362454208011

In [82]:
print("Percentage of Dining Rating Missing = ", ((df["Dining_Rating"].isna().sum()) / len(df))*100)

Percentage of Dining Rating Missing =  26.068884090670156

In [83]:
print("Percentage of Delivery Rating Missing = ", ((df["Delivery_Rating"].isna().sum()) / len(df))*100)

Percentage of Delivery Rating Missing =  1.0351213437168942

In [84]:
print("Duplicate Rows = ",df.duplicated().sum())

Duplicate Rows =  22127